# Generated by Django 3.1.6 on 2021-03-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210317_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='user_details',
        ),
    ]
