# Generated by Django 3.1.6 on 2021-03-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_useraddress_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='profession',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
