# Generated by Django 3.1.6 on 2021-03-28 12:04

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210328_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(blank=True, max_length=150, null=True)),
                ('mobileno', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('profession', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'contacts',
                'managed': False,
            },
        ),
    ]
