# Generated by Django 3.1.7 on 2021-04-04 11:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210328_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('mobileno', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('profession', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
    ]
