# Generated by Django 3.1.6 on 2021-04-25 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_contacts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdetails',
            unique_together=set(),
        ),
    ]
