# Generated by Django 3.1.7 on 2021-04-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={},
        ),
    ]
